var loud = args[1] === undefined ? 1 : args[1]

function whisper(msg) {
  if (loud == 1) {
    tprint(msg)
  } else {
    print(msg)
  }
}

function getAccess(target) {
  if (hasRootAccess(target)) {
    whisper("Have root access already");
    return;
  }

  if (fileExists("BruteSSH.exe", "home")) {
    brutessh(target)
    whisper("Broke SSH port")
  }
  if (fileExists("FTPCrack.exe", "home")) {
    ftpcrack(target)
    whisper("Broke FTP port")
  }
  if (fileExists("HTTPWorm.exe", "home")) {
    httpworm(target)
    whisper("HTTPWorm-ed port")
  }
  if (fileExists("relaySMTP.exe", "home")) {
    relaysmtp(target)
    whisper("Broke SMTP port")
  }
  if (fileExists("sqlinject.exe", "home")) {
    sqlinject(target)
    whisper("Broke SQL port")
  }

  var ret = nuke(target)
  whisper("Sudo aquired: " + ret)
}

getAccess( args[0])
